### ISSUE TITLE
안녕하세요! 제이스님!

### ISSUE THREAD

**Issue by BangJihoon** [ParkHeeseung/ParkHeeseung.github.io#1]
예전에 오키를 통해서 제이스님 포폴페이지를 처음 보게되어 들어왔습니다!

github io 페이지가 너무 이쁘고 깔끔해서 언젠가 어떻게 만드신건지 여쭤보고 싶었는데,

해당 페이지를 템플릿을 기반으로 커스텀해서 저만의 포트폴리오 페이지를 만들고 싶습니다.

해당 소스를 제 개인적인 github io 페이지로 사용해도 괜찮을까요?..

**Comment by ParkHeeseung** [comment]
네 자유롭게 사용해도 됩니다:)
